apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pricing-service-hpa
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pricing-service
  targetCPUUtilizationPercentage: 60