version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: scrapzee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 10

  auth-service:
    build: ./auth
    container_name: scrapzee-auth
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/scrapzee_auth
      SECRET_KEY: super-secret-key-change-this
    ports:
      - "5001:5001"

  pricing-service:
    build: ./pricing
    container_name: scrapzee-pricing
    depends_on:
      - mysql
      - auth-service
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/scrapzee_pricing
      AUTH_SERVICE_URL: http://auth-service:5001
    ports:
      - "5002:5002"

  user-service:
    build: ./users
    container_name: scrapzee-users
    depends_on:
      - mysql
      - auth-service
      - pricing-service
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/scrapzee_users
      AUTH_SERVICE_URL: http://auth-service:5001
      PRICING_SERVICE_URL: http://pricing-service:5002
    ports:
      - "5003:5003"

  frontend:
    build: ./frontend
    container_name: scrapzee-frontend
    depends_on:
      - auth-service
      - pricing-service
      - user-service
    ports:
      - "3000:80"

volumes:
  mysql_data:
