services:
  mysql:
    image: mysql:8
    container_name: scrapzee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: scrapzee-auth
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/scrapzee_auth
      SECRET_KEY: super-secret-key-change-this
    ports:
      - "5001:5001"

  pricing-service:
    build: ./pricing-service
    container_name: scrapzee-pricing
    depends_on:
      - mysql
      - auth-service
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/scrapzee_pricing
      AUTH_SERVICE_URL: http://auth-service:5001
    ports:
      - "5002:5002"

  user-service:
    build: ./user-service
    container_name: scrapzee-users
    depends_on:
      - mysql
      - auth-service
      - pricing-service
    environment:
      DATABASE_URL: mysql+pymysql://root:password@mysql/scrapzee_users
      AUTH_SERVICE_URL: http://auth-service:5001
      PRICING_SERVICE_URL: http://pricing-service:5002
    ports:
      - "5003:5003"

volumes:
  mysql_data:
