apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  
  - secrets/scrapzee-secrets.yaml

  - deployments/frontend.yaml
  - deployments/auth-service.yaml
  - deployments/dealer-service.yaml
  - deployments/user-service.yaml
  - deployments/pricing-service.yaml
  - deployments/mysql.yaml

  - services/frontend-svc.yaml
  - services/auth-svc.yaml
  - services/dealer-svc.yaml
  - services/user-svc.yaml
  - services/pricing-svc.yaml
  - services/mysql-svc.yaml

  - ingress/ingress.yaml

  - network-policies/1-default-deny-all.yaml
  - network-policies/2-allow-dns-egress.yaml
  - network-policies/3-allow-frontend.yaml
  - network-policies/4-allow-auth.yaml
  - network-policies/5-allow-dealer.yaml
  - network-policies/6-allow-user.yaml
  - network-policies/7-allow-pricing.yaml
  - network-policies/8-allow-mysql.yaml
  - network-policies/9-allow-backend-to-mysql-egress.yaml
  - network-policies/10-allow-backend-to-backend.yaml

  - hpa/auth-hpa.yaml
  - hpa/user-hpa.yaml
  - hpa/dealer-hpa.yaml
  - hpa/pricing-hpa.yaml
  - hpa/frontend-hpa.yaml
